# Generated by Django 5.1.2 on 2024-10-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_chapter_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='text_content',
            field=models.TextField(blank=True),
        ),
    ]
