# Generated by Django 5.1.2 on 2024-10-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseprogress_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='last_accessed',
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
