# Generated by Django 5.1.2 on 2024-10-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_courseprogress_last_accessed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='viewed_lessons',
            field=models.IntegerField(default=0),
        ),
    ]
