# Generated by Django 5.1.2 on 2024-10-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='powerpoint_file',
            field=models.FileField(blank=True, upload_to='powerpoints/'),
        ),
    ]
