# Generated by Django 5.1.2 on 2024-10-28 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_chapter_powerpoint_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='powerpoint_file',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='video_file',
        ),
        migrations.CreateModel(
            name='ChapterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chapter_files/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('ppt', 'PowerPoint'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=10)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.chapter')),
            ],
        ),
    ]
