# Generated by Django 5.1.2 on 2024-10-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_chapter_options_remove_chapter_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='powerpoint_file',
            field=models.FileField(blank=True, upload_to='powerpoints/'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='video_file',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.DeleteModel(
            name='ChapterFile',
        ),
    ]
